Target ES6 properly
jellyfin/jellyfin-sdk-typescript pull request #341
Opened 2022-11-29 14:33 UTC by ferferga

See my previous fix at generator: https://github.com/OpenAPITools/openapi-generator/pull/10308

See https://www.typescriptlang.org/tsconfig#target and https://www.typescriptlang.org/tsconfig#module

```
Default:
CommonJS if target is ES3 or ES5,,ES6/ES2015 otherwise.
```

There's no tree shaking right now

2022-12-03 16:59 UTC, thornbill requested changes
Could you add a note in the breaking changes section of the README also? Thanks!

2022-12-03 16:59 UTC, thornbill commented on tsconfig.json
> +    "target": "ES6",
I think we should be using ES2015 since that is the "correct" versioning for anything beyond ES5.

2022-12-04 22:42 UTC, ferferga commented
@thornbill I took the liberty to also add the upgrade to Axios v1 at #300 to the breaking changes section.

I also used 0.8.0 as the next logical step, but please ping me if you want me to use another versioning and I can fix it without any problem.

2022-12-05 17:40 UTC, thornbill approved these changes

2022-12-05 17:55 UTC, merged