Drop compare-versions dependency
jellyfin/jellyfin-sdk-typescript pull request #459
Opened 2023-04-13 10:15 UTC by ferferga

The version check we needed is simple enough to implement ourselves, shaving off some bytes from the bundle size consumers will have when using the SDK

2023-04-13 14:50 UTC, thornbill commented
Looks pretty good! I think it should include some handling for invalid strings. It would be nice to have some unit tests to cover invalid values also.

2023-04-13 15:15 UTC, ferferga commented
@thornbill What do you think we should return when one of the passed versions are invalid? `undefined` or `true`?

2023-04-13 15:18 UTC, ThibaultNocchi commented
@ferferga I think you should throw?

2023-04-13 15:59 UTC, nielsvanvelzen commented
Some parts of the Jellyfin server may include a build number in a version field. So a version can be `10.8.10.0`. I think this primarily happens with plugin versions.

2023-04-13 16:47 UTC, ferferga commented
@thornbill Hopefully these tests are enough for most use cases!
@nielsvanvelzen For the time being, I think we should keep this function scoped to just checking the Jellyfin server version. We don't even have logic for checking if the version is bigger or equals, as the only usage we had in the SDK was to check if a version was inferior only.

2023-04-19 02:32 UTC, thornbill requested changes
It helps if I actually submit the review comments I write... 😅

2023-04-19 02:32 UTC, thornbill commented on src/discovery/recommended-server-discovery.ts
> +	} else if (isVersionLess(version, MINIMUM_VERSION)) {
We should probably catch the invalid version error here and return a different server issue.

2023-04-27 12:52 UTC, ferferga commented on src/discovery/recommended-server-discovery.ts
> +	} else if (isVersionLess(version, MINIMUM_VERSION)) {
@thornbill Instead of creating a new issue type, I reused the VersionUnsupportedIssue, since isVersionLess should only catch if the version doesn't follow the X.Y.Z schema. I guess this should be significante enough for the developer using the SDK.

If you still want a new issue type defined, please let me know.

2023-04-27 15:14 UTC, thornbill commented on src/discovery/recommended-server-discovery.ts
> +	} else if (isVersionLess(version, MINIMUM_VERSION)) {
Sounds great thanks!

2023-05-10 14:10 UTC, thornbill commented on src/discovery/recommended-server-discovery.ts
> +			scores.push(RecommendedServerInfoScore.OK);
I've been thinking about this and I think it would be better to use `VersionMissing` with a `BAD` score here. What do you think?

2023-05-10 15:53 UTC, ferferga commented on src/discovery/recommended-server-discovery.ts
> +			scores.push(RecommendedServerInfoScore.OK);
@thornbill Sure! Pushed a new commit, I can squash with the others if you prefer it!

2023-05-10 23:41 UTC, thornbill approved these changes

2023-05-10 23:43 UTC, merged